export {texts} from './texts'
export {UNIVERSITY_BASE_ROUTE, FIELD_OF_STUDY_BASE_ROUTE, PERIOD_BASE_ROUTE, GET_APPLICATIONS_BY_FILTER,
    GET_PROCESSED_FILE_ROUTE, GET_APPLICATION_SCHEMA_ROUTE, CREATE_APPLICATION_SCHEMA_ROUTE,
    STUDY_MODE_BASE_ROUTE, COMPETITION_TYPE_BASE_ROUTE, CHECK_CAN_PROCESS_FILE_ROUTE, REMOVE_APPLICATION_ROUTE,
    EDIT_APPLICATION_SCHEMA_ROUTE, ADD_PERIOD_ROUTE , EDIT_PERIOD_ROUTE, REMOVE_PERIOD_ROUTE} from './routes'