const russianTexts = {
    comboBoxNoResult: 'Нет результатов',
    loading: 'Загрузка...',
    chooseStudyMode: 'Формат обучения',
    chooseCompetitionType: 'Основание поступления',
    choosePeriod: "Период поступления",
    university: 'Университет',
    city: 'Город',
    fieldOfStudy: 'Направление обучения',
    program: 'Образовательная программа',
    name: 'Название',
    input: "Введите",
    choose: 'Выберите',
    select: "Выбрать",
    inputName: "Введите название",
    back: 'Назад',
    budget: 'Количество бюджетных мест',
    commercial: "Количество платных мест",
    targeted: 'Количество целевых мест',
    check: 'Проверить',
    chooseFile: "Выберите файл...",
    done: "Готово",
    save: "Сохранить",
    found: "Найдено"
}

export const texts = {
    comboBoxNoResult: russianTexts.comboBoxNoResult,
    loading: russianTexts.loading,
    chooseStudyMode: russianTexts.chooseStudyMode,
    chooseCompetitionType: russianTexts.chooseCompetitionType,
    choosePeriod: russianTexts.choosePeriod,
    university: russianTexts.university,
    city: russianTexts.city,
    fieldOfStudy: russianTexts.fieldOfStudy,
    name: russianTexts.name,
    input: russianTexts.input,
    program: russianTexts.program,
    choose: russianTexts.choose,
    select: russianTexts.select,
    inputName: russianTexts.inputName,
    back: russianTexts.back,
    budget: russianTexts.budget,
    commercial: russianTexts.commercial,
    targeted: russianTexts.targeted,
    check: russianTexts.check,
    chooseFile: russianTexts.chooseFile,
    done: russianTexts.done,
    save: russianTexts.save,
    found: russianTexts.found,
}