export {StoreService} from './storeService'
export {OrdinaryService} from './ordinaryService'
export {PartialService} from './partialService'
export {Store} from './store'
export {ServiceBase} from './serviceBase'